import re
import pypresence
import time
import psutil
import sys

gameTypes = {
    'FT_WILD' : 'Wild',
    'FT_STANDARD' : 'Standard'
}

stateComplem = { 
    'GT_VS_AI' : 'Dungeon',
    'GT_RANKED' : 'Ranked: []',
    'GT_TAVERNBRAWL' : 'Tavern Brawl',
    'GT_TUTORIAL' : 'Tutorial',
    'GT_UNRANKED' : 'Casual: []',
    'GT_ARENA' : 'Arena'
}

gameModes = {
    'GT_VS_AI' : 'Playing versus AI',
    'GT_RANKED' : 'Playing ranked',
    'GT_VS_FRIEND' : 'Playing versus a friend',
    'GT_TAVERNBRAWL' : 'Doing Tavern Brawl',
    'GT_TUTORIAL' : 'Doing tutorial',
    'GT_UNRANKED' : 'Playing unranked',
    'GT_ARENA' : 'Doing Arena run'
}

images = {
    'GT_VS_AI' : 'normal',
    'GT_RANKED' : 'normal',
    'GT_VS_FRIEND' : 'normal',
    'GT_TAVERNBRAWL' : 'brawl',
    'GT_TUTORIAL' : 'normal',
    'GT_UNRANKED' : 'normal',
    'GT_ARENA' : 'arena'
}

clientID = '528679932415442965'


class richPresence:
    def __init__(self, clientId):
        self.RPC = pypresence.Presence(clientId)
        self.connected = False

    def start(self):
        self.connect()

    def connect(self):
        if self.connected == False:
            self.RPC.connect()
            self.connected = True

    def disconnect(self):
        if self.connected:
            self.RPC.close()
            self.connected = False

    def update(self, **kwargs):
        self.RPC.update(**kwargs)


class HearthstoneRPC:
    def __init__(self):
        self.rpc = richPresence(clientID)
        #self.rpc.start()
        self.log = None # Hearthstone Log
        self.spectating = False # True if user is spectating, False if not
        self.gamemode = None # Game mode (Player vs AI, Player vs Player, Player vs Friend)
        self.type = None # Game type (Standart/Wild)
        self.playerSpectated = None # Player user is spectating
        self.playerName = None # Player name
        self.opponentName = None # Opponent name
        self.lastLine = 0 # Last line read
        self.playing = False # If player is in a match
        self.lastMessage = None # Last message generated by format_message
        self.message = None # Message generated by format_message
        self.timer = 0 # Time elapsed
        self.gamePID = None # Hearthstone pid
        self.pids = []
        self.spammerBlock = False # Blocks repetitive messages
        self.spammerBlocker = False # Blocks other repetitive messages 

    def reset(self):
        self.rpc = richPresence(clientID)
        self.log = None
        self.spectating = False
        self.gamemode = None
        self.type = None
        self.playerSpectated = None 
        self.playerName = None
        self.opponentName = None 
        self.lastLine = 0 
        self.playing = False 
        self.lastMessage = None 
        self.message = None 
        self.timer = 0
        self.spammerBlock = False

    def stop(self):
        print('[HSRPC] Exiting...')
        try:
            self.rpc.close()
        except:
            pass
        time.sleep(1)
        sys.exit(0)

    def start(self):
        print('[HSRPC] Initializing Hearthstone Discord rich presence...')
        print('[HSRPC] Done!')
        while True:
            self.scan_pids()
            if self.gamePID not in self.pids:
                ##print('Hearthstone not open')
                self.rpc.disconnect()
                self.reset()
                if self.spammerBlocker == False:
                    print('[HSRPC] Hearthstone is closed!')
                    self.spammerBlocker = True
                    self.spammerBlock = False
                time.sleep(5)
                continue
            if self.spammerBlock == False:
                print('[HSRPC] Hearthstone is open! Stablishing connection to discord.')
                self.spammerBlock = True
                self.spammerBlocker = False
            self.rpc.start()
            self.scan_log()
            self.reader()
            self.lastMessage = self.message
            self.message = self.format_messages()
            ##print(self.message)
            try:
                if self.playing or self.spectating:
                    typeGame = stateComplem[self.gamemode].replace('[]', gameTypes[self.type])
                else:
                    typeGame = None
            except:
                typeGame = None
            try:
                if self.playing == False:
                    largeImage = 'menu'
                else:
                    largeImage = images[self.gamemode]
            except:
                largeImage = 'hearthstonelogo'
            if self.lastMessage != self.message:
                self.timer = int(time.time())
            self.rpc.update(details=self.message, state=typeGame, large_image=largeImage, large_text='Playing Hearthstone', start=self.timer)
            time.sleep(15)

    def scan_pids(self):
        for programs in psutil.process_iter():
            if programs.pid not in self.pids:
                self.pids.append(programs.pid)
            if programs.name() == 'Hearthstone.exe':
                self.gamePID = programs.pid
                return
            else:
                self.gamePID = None 

    def format_messages(self):
        if self.spectating:
            return 'Spectating friend'
        elif self.playing:
            return f'{gameModes[self.gamemode]}'
        elif self.playing == False:
            self.type = None
            return 'Idle'
    
    def fix_logger(self, length):
        if length < self.lastLine:
            self.lastLine = 0

    def scan_log(self):
        logger = open(r'C:\Program Files (x86)\Hearthstone\Logs\Power.log', 'r')
        self.log = logger.readlines()
        self.fix_logger(len(self.log))
        logger.close()
    
    def reader(self):
        lastIndex = self.lastLine
        for lineIndex in range(self.lastLine, len(self.log)):
            line = self.log[lineIndex]
            if re.search(r'GameType=', line) != None:
                self.get_gamemode(line)
            if re.search(r'FormatType=', line) != None:
                self.get_type(line)
            if re.search(r'PlayerName=', line) != None:
                self.get_player_names(line)
            if re.search(r'Spectating', line) != None or re.search(r'Spectator Mode', line) != None:
                self.spectate(line)
            if re.search(r'value=FINAL_GAMEOVER', line) != None:
                self.detect_end(line)
            lastIndex += 1
        self.lastLine = lastIndex

    def get_gamemode(self, line):
        index = re.search(r'GameType=', line).span()[1]
        maxIndex = len(line)
        self.gamemode = line[index : maxIndex].strip('\n')
        #print(self.gamemode)
        return

    def get_type(self, line):
        index = re.search(r'FormatType=', line).span()[1]
        maxIndex = len(line)
        self.type = line[index : maxIndex].strip('\n')
        #print(self.type)
        return

    def spectate(self, line):
        if re.search(r'Begin', line) != None:
            index = re.search(r'Begin Spectating', line).span()[1]+1
            maxIndex = index+3
            self.spectating = True
            #print('Spectating friend')
        elif re.search(r'End', line):
            self.spectating = False
            #print('Stopped spectating')
        return

    def detect_end(self, line):
        self.playing = False
        return

    def get_player_names(self, line):
        index = re.search(r'PlayerName=', line).span()[1]
        maxIndex = len(line)
        if self.spectating == False:
            self.playing = True
            self.playerSpectated = None
            if line[index : maxIndex].strip('\n') == self.playerName:
                return
            else:
                self.opponentName = line[index : maxIndex].strip('\n')
                ##print(f'[{self.playerName}] Playing against {self.opponentName}')
            return
        else:
            if line[index:maxIndex].strip('\n') != 'UNKNOWN HUMAN PLAYER' and self.playerSpectated == None:
                self.playerSpectated = line[index:maxIndex]
                #print(f'Spectating {self.playerSpectated}')
            self.opponentName = None

if __name__ == '__main__':
    rpc = HearthstoneRPC()
    rpc.start()
